
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Student
 */
public class Logform extends javax.swing.JFrame {

    /**
     * Creates new form Logform
     */
    public Logform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton3 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        teacher = new javax.swing.JRadioButton();
        student = new javax.swing.JRadioButton();
        admin = new javax.swing.JRadioButton();
        idl = new javax.swing.JLabel();
        passl = new javax.swing.JLabel();
        yearl = new javax.swing.JLabel();
        bl = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        year = new javax.swing.JComboBox<>();
        br = new javax.swing.JComboBox<>();
        st = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jRadioButton3.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setBackground(new java.awt.Color(204, 153, 0));
        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Timetable Management Software");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setFocusable(false);
        jLabel1.setOpaque(true);

        teacher.setBackground(new java.awt.Color(153, 0, 153));
        buttonGroup1.add(teacher);
        teacher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        teacher.setForeground(new java.awt.Color(255, 153, 0));
        teacher.setText("Teacher");
        teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionPerformed(evt);
            }
        });

        student.setBackground(new java.awt.Color(153, 0, 153));
        buttonGroup1.add(student);
        student.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        student.setForeground(new java.awt.Color(255, 153, 0));
        student.setText("Student");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });

        admin.setBackground(new java.awt.Color(153, 0, 153));
        buttonGroup1.add(admin);
        admin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 153, 0));
        admin.setText("Admin");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        idl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        idl.setForeground(new java.awt.Color(255, 153, 0));
        idl.setText("ID:");
        idl.setEnabled(false);

        passl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passl.setForeground(new java.awt.Color(255, 153, 0));
        passl.setText("Password:");
        passl.setEnabled(false);

        yearl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yearl.setForeground(new java.awt.Color(255, 153, 0));
        yearl.setText("Year:");
        yearl.setEnabled(false);

        bl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bl.setForeground(new java.awt.Color(255, 153, 0));
        bl.setText("Branch:");
        bl.setEnabled(false);

        id.setEnabled(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2014", "2015", "2016" }));
        year.setEnabled(false);
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        br.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSC", "CSE", "ECE", "MEC", "CVL" }));
        br.setEnabled(false);

        st.setText("Show Timetable/Login");
        st.setEnabled(false);
        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });

        pass.setEchoChar('*');
        pass.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(teacher)
                .addGap(179, 179, 179)
                .addComponent(student)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(admin)
                .addGap(77, 77, 77))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bl)
                            .addComponent(yearl)
                            .addComponent(passl)
                            .addComponent(idl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(br, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher)
                    .addComponent(student)
                    .addComponent(admin))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idl)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passl)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearl)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bl)
                    .addComponent(br, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(st)
                .addGap(49, 49, 49))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("EXIT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("About Us");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionPerformed
        id.setEnabled(true);
        pass.setEnabled(true);
        idl.setEnabled(true);
        passl.setEnabled(true);
        yearl.setEnabled(true);
        year.setEnabled(true);
        st.setEnabled(true);
        bl.setEnabled(true);
        br.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_teacherActionPerformed

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed
        if (teacher.isSelected()) {
            String us = (String) id.getText();  //getting username
            String ps = pass.getText();  //getting password
            String yr = (String) year.getSelectedItem();
            System.out.println(yr);//getting year
            String bran = (String) br.getSelectedItem();
            {
                try {
                    Class.forName("java.sql.DriverManager");
                    Connection C = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable", "root", "root");
                    Statement S = (Statement) C.createStatement();
                    String query = "select * from teacher where teacher_id='" + us + "';";
                    ResultSet r = S.executeQuery(query);
                    r.next();
                    String pwd = r.getString("password");  //getting password from database
                    String user = r.getString("teacher_id");  //getting username from database
                    String teacher_year = r.getString("year");
                    String branche = r.getString("branch");
                    if (us.equalsIgnoreCase(user)) //matching application username with database username
                    {
                        if (ps.equals(pwd)) //matching application password with database password
                        {
                            if (yr.equalsIgnoreCase(teacher_year)) {
                                if (bran.equalsIgnoreCase(branche)) {
                                    this.setVisible(false);
                                    new teachertable(us, yr, bran).setVisible(true);
                                } else {
                                    JOptionPane.showMessageDialog(this, "Incorrect branch!", "error", 0);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Incorrect year!", "error", 0);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Incorrect Password!", "error", 0);
                        }
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Incorrect Teacher ID", "error", 0);
                }
            }
        } else if (student.isSelected()) {
            String us = (String) id.getText();  //getting username
            String yr = (String) year.getSelectedItem();//getting year
            String branch = (String) br.getSelectedItem();
            {
                try {
                    Class.forName("java.sql.DriverManager");
                    Connection C = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable", "root", "root");
                    Statement S = (Statement) C.createStatement();
                    String query = "select * from student where student_id='" + us + "';";
                    ResultSet r = S.executeQuery(query);
                    r.next();
                    String bran = r.getString("student_branch");  //getting password from database
                    String user = r.getString("student_id");  //getting username from database
                    String student_year = r.getString("student_year");
                    if (us.equalsIgnoreCase(user)) //matching application username with database username
                    {
                        if (yr.equals(student_year)) //matching application password with database password
                        {
                            if (branch.equalsIgnoreCase(bran)) {
                                this.setVisible(false);
                                new Student_table(yr, bran).setVisible(true);
//                                new teachertable(us);

                            } else {
                                JOptionPane.showMessageDialog(this, "Incorrect Branch!", "error", 0);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Incorrect Year!", "error", 0);
                        }
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Incorrect Student ID", "error", 0);
                }
            }
        } else if (admin.isSelected()) {
            String admid = id.getText();
            String admp = pass.getText();
            if (admid.equals("ADMIN") && admp.equals("BMU1234")) {
                this.setVisible(false);
                new Admin().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect Username/Password!");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_stActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        id.setEnabled(true);
        idl.setEnabled(true);
        passl.setEnabled(false);
        pass.setEnabled(false);
        yearl.setEnabled(true);
        year.setEnabled(true);
        st.setEnabled(true);
        bl.setEnabled(true);
        br.setEnabled(true);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_studentActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        id.setEnabled(true);
        idl.setEnabled(true);
        passl.setEnabled(true);
        pass.setEnabled(true);
        st.setEnabled(true);
        yearl.setEnabled(false);
        year.setEnabled(false);

        bl.setEnabled(false);
        br.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new About_Us().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int a=JOptionPane.showConfirmDialog(this,"Do you want to exit","EXIT",0);
if(a==0){
System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin;
    private javax.swing.JLabel bl;
    private javax.swing.JComboBox<String> br;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel passl;
    private javax.swing.JButton st;
    private javax.swing.JRadioButton student;
    private javax.swing.JRadioButton teacher;
    private javax.swing.JComboBox<String> year;
    private javax.swing.JLabel yearl;
    // End of variables declaration//GEN-END:variables
}
