
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Student
 */
public class timetableformation extends javax.swing.JFrame {

    /**
     * Creates new form timetableformation
     */
    public timetableformation() {
        initComponents();
    }
    String xyz, xyz1;

    public timetableformation(String a, String b) {
        initComponents();
        xyz = a;
        xyz1 = b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        subj = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tt = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tt1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add Class");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        subj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Subject" }));

        jLabel1.setText("Select Subject:");

        jLabel2.setText("Select Day:");

        dt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }));

        jLabel3.setText("Select Time:");

        tt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Time" }));

        jLabel4.setText("Select Class:");

        tt1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Class" }));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("LOAD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("LOAD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tt1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subj, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String subject = (String) subj.getSelectedItem();
        String Day = (String) dt.getSelectedItem();
        String Time = (String) tt.getSelectedItem();
        String venue = (String) tt1.getSelectedItem();
String teacher_id;
        {try {
            Class.forName("java.sql.DriverManager");
            Connection C = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable", "root", "root");
            Statement S = (Statement) C.createStatement();
            String query="Select teacher_id from teacher where subject='"+subject+"';";
            
            ResultSet rs = S.executeQuery(query);
            rs.next();
            teacher_id=rs.getString("teacher_id");
            String query1 ="UPDATE "+xyz1+"_"+xyz+" SET "+Time+"= '"+teacher_id+" "+subject+" "+venue+"' WHERE DAY ='"+Day+"';";
        S.executeUpdate(query1);
        String query2="UPDATE "+venue+ " SET "+Time+"='0' WHERE DAY ='"+Day+"';";
        S.executeUpdate(query2);
        }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            }}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        {
            try {
                Class.forName("java.sql.DriverManager");
                Connection C = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable", "root", "root");
                Statement S = (Statement) C.createStatement();
                String query1 = "Select * from subjects where course= '" + xyz + "';";
                ResultSet rs1 = S.executeQuery(query1);
                while (rs1.next()) {
                    String subjects = rs1.getString("subjects");
                    subj.addItem(subjects);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String a = (String) dt.getSelectedItem();
        String b, c, d, k, f, g, h, i, j;
        try {
            Class.forName("java.sql.DriverManager");
            Connection C = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable", "root", "root");
            Statement S = (Statement) C.createStatement();
            String query1 = "Select * from " + xyz1 + "_" + xyz + " where day='" + a + "';";
            ResultSet rs1 = S.executeQuery(query1);
            while (rs1.next()) {
                b = rs1.getString("9_9_50");
                c = rs1.getString("10_10_50");
                d = rs1.getString("11_11_50");
                k = rs1.getString("12_12_50");
                f = rs1.getString("1_1_50");
                g = rs1.getString("2_2_50");
                h = rs1.getString("3_3_50");
                i = rs1.getString("4_4_50");
                j = rs1.getString("5_5_50");

                if (b.equals("")) {
                    tt.addItem("9_9_50");
                }
                if (c.equals("")) {
                    tt.addItem("10_10_50");
                } 
                if (d.equals("")) {
                    tt.addItem("11_11_50");
                }
                if (k.equals("")) {
                    tt.addItem("12_12_50");
                }
                if (f.equals("")) {
                    tt.addItem("1_1_50");
                }
                if (g.equals("")) {
                    tt.addItem("2_2_50");
                }
                if (h.equals("")) {
                    tt.addItem("3_3_50");
                }
                if (i.equals("")) {
                    tt.addItem("4_4_50");
                }
                if (j.equals("")) {
                    tt.addItem("5_5_50");
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String a = (String) tt.getSelectedItem();
        String x = (String) dt.getSelectedItem();
        String b, c, d, k, f, g, h, i, j;
        try {
            Class.forName("java.sql.DriverManager");
            Connection C = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable", "root", "root");
            Statement S = (Statement) C.createStatement();
            String query1 = "Select " + a + " from ga104 where day = '" + x + "';";
            ResultSet rs1 = S.executeQuery(query1);
            while (rs1.next()) {
                b = rs1.getString(a);
                if (b.equals("1")) {
                    tt1.addItem("GA104");
                }
            }

            String query2 = "Select " + a + " from ga105 where day = '" + x + "';";
            ResultSet rs2 = S.executeQuery(query2);
            while (rs2.next()) {
                b = rs2.getString(a);
                if (b.equals("1")) {
                    tt1.addItem("GA105");
                }
            }
            
            String query3 = "Select " + a + " from ga106 where day = '" + x + "';";
            ResultSet rs3 = S.executeQuery(query3);
            while (rs3.next()) {
                b = rs3.getString(a);
                if (b.equals("1")) {
                    tt1.addItem("GA106");
                }
            }
            
            String query4 = "Select " + a + " from ga204 where day = '" + x + "';";
            ResultSet rs4 = S.executeQuery(query4);
            while (rs4.next()) {
                b = rs4.getString(a);
                if (b.equals("1")) {
                    tt1.addItem("GA204");
                }
            }
            
            String query5 = "Select " + a + " from ga205 where day = '" + x + "';";
            ResultSet rs5 = S.executeQuery(query5);
            while (rs5.next()) {
                b = rs5.getString(a);
                if (b.equals("1")) {
                    tt1.addItem("GA205");
                }
            }
            
            String query6 = "Select " + a + " from ga206 where day = '" + x + "';";
            ResultSet rs6 = S.executeQuery(query6);
            while (rs6.next()) {
                b = rs6.getString(a);
                if (b.equals("1")) {
                    tt1.addItem("GA206");
                }
            }
            
            String query7 = "Select " + a + " from ga207 where day = '" + x + "';";
            ResultSet rs7 = S.executeQuery(query7);
            while (rs7.next()) {
                b = rs7.getString(a);
                if (b.equals("1")) {
                    tt1.addItem("GA207");
                }
            }
            
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
tt.removeAllItems();
tt.addItem("Choose Time");
tt.setSelectedItem("Choose Time");
tt1.removeAllItems();
tt1.addItem("Choose Time");
tt1.setSelectedItem("Choose Time");// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int a=JOptionPane.showConfirmDialog(this,"Do you want to exit","EXIT",0);
if(a==0){
System.exit(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timetableformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timetableformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timetableformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timetableformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timetableformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> subj;
    private javax.swing.JComboBox<String> tt;
    private javax.swing.JComboBox<String> tt1;
    // End of variables declaration//GEN-END:variables
}
